### PR TITLE
Seth

### PR DESCRIPTION
**Pull request by SJTechy**

### CODE REVIEW

**Comment by masiamj** [comment]
@SJTechy it looks like `main` wasn't merged into `seth` fully. Please hit the `Update Branch` button and make sure the Vercel build is passing then it looks good. Thanks!

**Comment by SJTechy** [comment]
Done! Thanks!

**Review by kenjiw360 — APPROVED** [review]
This works just fine. Nothing wrong

**Review by laggycomputer — APPROVED** [review]
amogus

**Review by masiamj — APPROVED** [review]

**Pull request merged**
